import React,{useEffect,useState} from "react";
import{createRoot}from"react-dom/client";
import{motion,AnimatePresence,useReducedMotion}from"framer-motion";
import{ArrowUpRight,ArrowLeft,Search,Menu,X}from"lucide-react";
import gsap from"gsap";
import{sciences}from"./data";
import{Explorer}from"./Explorer";
import{ScienceExplorer}from"./ScienceExplorer";
import"./style.css";
function App(){const[page,setPage]=useState<string>("home");const[query,setQuery]=useState("");const[menu,setMenu]=useState(false);const reduced=useReducedMotion();useEffect(()=>{if(reduced)return;gsap.fromTo(".brand-mark",{rotate:-20,opacity:0},{rotate:0,opacity:1,duration:1,ease:"back.out(2)"})},[reduced]);const go=(p:string)=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:reduced?"auto":"smooth"})};const filtered=sciences.filter(s=>(s.name+" "+s.en+" "+s.description).toLowerCase().includes(query.toLowerCase()));return <div className="app"><header className="header"><button className="brand" onClick={()=>go("home")} aria-label="На главную"><span className="brand-mark">✳</span> ROADMAP<span>SCIENCE</span></button><nav className={menu?"nav visible":"nav"} aria-label="Навигация"><button onClick={()=>go("home")}>Обзор</button><a href="https://github.com/kumofsoc/RoadmapScience" target="_blank" rel="noreferrer">GitHub <ArrowUpRight size={14}/></a></nav><button className="menu" aria-label={menu?"Закрыть меню":"Открыть меню"} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header><AnimatePresence mode="wait"><motion.main key={page} initial={reduced?false:{opacity:0,y:15}} animate={{opacity:1,y:0}} exit={reduced?undefined:{opacity:0,y:-12}} transition={{duration:.35}}>{page==="home"?<><section className="catalog" id="disciplines"><div className="section-top"><div><h2>Науки и дисциплины<span className="period">.</span></h2></div><div className="search"><Search size={17}/><input aria-label="Поиск дисциплин" placeholder="Поиск дисциплины..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="science-grid">{filtered.map((s,i)=><motion.button whileHover={reduced?undefined:{y:-5}} key={s.id} className={"science-card "+(!s.ready?"coming":"")} onClick={()=>go(s.id)}><div className="card-top"><span>{String(i+1).padStart(2,"0")} / {s.en}</span><ArrowUpRight size={18}/></div><div className="symbol">{s.symbol}</div><h3>{s.name}</h3><p>{s.description}</p><div className="card-bottom"><span>{s.en}</span><span>{s.ready?"ИССЛЕДОВАТЬ →":"В РАЗРАБОТКЕ"}</span></div></motion.button>)}</div>{filtered.length===0&&<p className="empty">Ничего не найдено.</p>}</section></>:<><section className="roadmap-hero"><button className="back" onClick={()=>go("home")}><ArrowLeft size={16}/> Все дисциплины</button></section>{page==="math"?<Explorer/>:<ScienceExplorer key={page} scienceId={page}/>}</>}</motion.main></AnimatePresence><footer><span className="brand footer-brand">✳ ROADMAP<span>SCIENCE</span></span><a href="https://github.com/kumofsoc/RoadmapScience" target="_blank" rel="noreferrer">OPEN SOURCE ↗</a></footer></div>}
createRoot(document.getElementById("root")!).render(<React.StrictMode><App/></React.StrictMode>);