import {useMemo,useState} from "react";
import {Search} from "lucide-react";
import {sciences} from "./data";
import {KnowledgeGraph,GraphNode} from "./KnowledgeGraph";
import "./explorer.css";
const branches:Record<string,string[][]>={
physics:[["Классическая механика","Аналитическая механика","Нелинейная динамика","Теория хаоса"],["Термодинамика","Статистическая физика","Фазовые переходы","Неравновесные системы"],["Электромагнетизм","Электродинамика","Квантовая электродинамика","Квантовая теория поля"],["Специальная относительность","Общая относительность","Космология","Квантовая гравитация"]],
cs:[["Дискретные структуры","Алгоритмы","Структуры данных","Теория сложности"],["Логические схемы","Архитектура ЭВМ","Операционные системы","Распределённые системы"],["Программирование","Языки и компиляторы","Формальные методы","Верификация"],["Вероятность и статистика","Машинное обучение","Глубокое обучение","Искусственный интеллект"]],
epistemology:[["Понятие знания","Обоснование","Проблема Геттиера","Современная эпистемология"],["Истина","Теории истины","Реализм и антиреализм","Социальная эпистемология"],["Скептицизм","Проблема индукции","Байесовская эпистемология","Формальная эпистемология"],["Восприятие","Свидетельство","Научное объяснение","Философия науки"]],
biology:[["Клеточная биология","Молекулярная биология","Генетика","Геномика"],["Анатомия","Физиология","Нейробиология","Системная биология"],["Эволюция","Популяционная генетика","Филогенетика","Эволюционная биология"],["Экология","Экосистемы","Биогеография","Биосфера"]],
chemistry:[["Строение атома","Химическая связь","Неорганическая химия","Координационная химия"],["Органическая химия","Механизмы реакций","Синтез","Химия полимеров"],["Термохимия","Физическая химия","Кинетика","Квантовая химия"],["Аналитическая химия","Спектроскопия","Электрохимия","Материаловедение"]],
philosophy:[["История философии","Онтология","Метафизика","Философия времени"],["Логика","Эпистемология","Философия науки","Философия математики"],["Этика","Метаэтика","Политическая философия","Прикладная этика"],["Философия языка","Философия сознания","Феноменология","Философия ИИ"]]
};
function topics(id:string){const science=sciences.find(s=>s.id===id)!;const fallback=[[science.name+" · основы",science.name+" · методы",science.name+" · теории",science.name+" · исследования"],["История и концепции","Ключевые модели","Современные подходы","Открытые вопросы"],["Наблюдение и данные","Аналитические методы","Моделирование","Сложные системы"],["Смежные дисциплины","Междисциплинарные связи","Прикладные направления","Новые исследования"]];return (branches[id]||fallback).flatMap((laneTopics,lane)=>laneTopics.map((title,stage):GraphNode=>({id:stage+"-"+lane,title,stage,lane,requires:stage===0?[]:[(stage-1)+"-"+lane]})))}
export function ScienceExplorer({scienceId}:{scienceId:string}){const science=sciences.find(s=>s.id===scienceId)!;const nodes=useMemo(()=>topics(scienceId),[scienceId]);const[active,setActive]=useState("0-0");const[query,setQuery]=useState("");const selected=nodes.find(n=>n.id===active)||nodes[0];const visible=nodes.filter(n=>n.title.toLowerCase().includes(query.toLowerCase()));const next=nodes.filter(n=>n.requires.includes(selected.id));return <section className="explorer"><div className="explorer-heading"><div><div className="eyebrow">{science.en} / ИНТЕРАКТИВНАЯ КАРТА</div><h2>{science.name}<span className="period">.</span></h2><p>{science.description}</p></div></div><div className="explorer-controls"><div className="explorer-search"><Search size={16}/><input aria-label="Поиск раздела" placeholder="Найти раздел..." value={query} onChange={e=>setQuery(e.target.value)}/></div></div><div className="explorer-layout"><div className="explorer-canvas as-map"><KnowledgeGraph nodes={visible} active={selected.id} onSelect={setActive}/></div><aside className="explorer-detail"><div className="eyebrow">РАЗДЕЛ</div><span className="detail-number">{String(selected.stage+1).padStart(2,"0")} / {String.fromCharCode(65+selected.lane)}</span><h3>{selected.title}</h3><div className="detail-section"><h4>Предшествующие связи</h4>{selected.requires.map(id=>{const n=nodes.find(n=>n.id===id)!;return <button className="prereq" key={id} onClick={()=>{setActive(id);setQuery("")}}>↳ {n.title}</button>})}</div><div className="detail-section"><h4>Продолжение направления</h4>{next.map(n=><button className="prereq" key={n.id} onClick={()=>{setActive(n.id);setQuery("")}}>→ {n.title}</button>)}</div></aside></div><p className="explorer-note">Обзорная структура дисциплины; связи носят ориентировочный характер.</p></section>}
